name: redis-stack
services:

  redis:
    hostname: redis.docker.local
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: [
      "--appendonly yes",
      "--port 0",
      "--tls-port 6379",
      "--tls-cert-file /certs/docker-local.crt",
      "--tls-key-file /certs/docker-local.key",
      "--tls-ca-cert-file /certs/docker-local.crt",
      "--tls-auth-clients no"
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "--tls", "--cacert", "/certs/docker-local.crt", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      redis-network:
        aliases:
          - redis.docker.local
    volumes:
      - vol_redis:/data
      - ${DOCKER_LOCAL_CERT_PATH:-$HOME/Github/docker-local-certs}/docker-local.crt:/certs/docker-local.crt:ro
      - ${DOCKER_LOCAL_CERT_PATH:-$HOME/Github/docker-local-certs}/docker-local.key:/certs/docker-local.key:ro

  redis-insight:
    hostname: redis-insight.docker.local
    container_name: redis-insight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    restart: unless-stopped
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_TLS_ENABLED=true
      - RI_REDIS_TLS_CA_PATH=/certs/docker-local.crt
    depends_on:
      redis:
        condition: service_healthy
    networks:
      redis-network:
        aliases:
          - redis-insight.docker.local
    volumes:
      - vol_redis_insight:/data
      - ${DOCKER_LOCAL_CERT_PATH:-$HOME/Github/docker-local-certs}/docker-local.crt:/certs/docker-local.crt:ro

networks:
  redis-network:
    driver: bridge

volumes:
  vol_redis:
  vol_redis_insight:
